default: &default
  adapter: mysql2
  charset: utf8mb4
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db
  strict: false

development:
  <<: *default
  database: cim_development

test:
  <<: *default
  database: cim_test

production:
  <<: *default
  database: cim_production
  username: cim
  password: <%= ENV["CIM_DATABASE_PASSWORD"] %>
